# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: joetancy
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Just some of my thoughts about tech dispersed into the servers that hosts the web.
twitter_username: joetancy
github_username: joetancy
minimal_mistakes_skin: default
search: true
repository: joetancy/joetancy.github.io
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Joe Tan :wave:"
  avatar : "/assets/images/bio-photo.jpeg"
  bio    : "I build applications :computer: and fix bugs :bug:. I learn photography :camera: in my free time. I am also a great DevOps engineer :wrench:. I write what I've learnt throught my career as a software engineer. :blush:"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/joetancy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joetancy"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/joetancy"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/joetancy"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/joetancy"
    - label: "Unsplash"
      icon: "fab fa-fw fa-unsplash"
      url: "https://unsplash.com/@joetancy/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/joetancy"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/joetancy"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/joetancy"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/joetancy"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/joetancy"
    - label: "Unsplash"
      icon: "fab fa-fw fa-unsplash"
      url: "https://unsplash.com/@joetancy/"
      
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
      
comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
